PRINT 'ROWCOUNT: ' + CAST(@@ROWCOUNT AS VARCHAR(10));
PRINT 'VERSION: ' + CAST(@@VERSION AS VARCHAR(100));
PRINT 'SPID: ' + CAST(@@SPID AS VARCHAR(10));
PRINT 'ERROR: ' + CAST(@@ERROR AS VARCHAR(10));
PRINT 'SERVERNAME: ' + CAST(@@SERVERNAME AS VARCHAR(100));
PRINT 'TRANCOUNT: ' + CAST(@@TRANCOUNT AS VARCHAR(10));
PRINT 'FETCH_STATUS: ' + CAST(@@FETCH_STATUS AS VARCHAR(10));
PRINT 'NESTLEVEL: ' + CAST(@@NESTLEVEL AS VARCHAR(10));
